### ISSUE TITLE
“Hatar” spelled wrong in cool gif

### ISSUE THREAD

**Issue by bird2498** [Exterminate5573/Exterminate5573#1]
Title

**Comment by RTXT25** [comment]
Yeah is supposed to be spelled “hater”

unless that is intentional

**Comment by RTXT25** [comment]
Wait it’s spelled correctly “Hatar” is a place in India

**Comment by bird2498** [comment]
No, Hatar should be spelled Határ. Like the place in Romania
There is no Hatar in India, there is Hatar in Iran and Pakistan what are you on abt

**Comment by RTXT25** [comment]
I forgot mate I google and then brain oof

**Comment by bird2498** [comment]
I win the internet argument

**Comment by bird2498** [comment]
Minor fact inaccuracy = win

**Comment by RTXT25** [comment]
Yes I win I had a minor fact inaccuracy

**Comment by RTXT25** [comment]
@Exterminate5573
Who wins

**Comment by Exterminate5573** [comment]
Balls

**Comment by RTXT25** [comment]
Ok

**Comment by bird2498** [comment]
No, you made the error
I win lol
